name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - newversion
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false 

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          
      - name: npm install, build, and test
        run: |
          cd azure-arc-jumpstart-app
          npm run fetch-docs  
          npm install
          npm run build
        env:
          CI: "" # need to fix this later

      - name: Zip artifact for deployment
        run: |
          cd azure-arc-jumpstart-app
          zip -r ../release.zip ./build/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./azure-arc-jumpstart-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'azure-arc-webapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_59507135515744FBA6986EDA6518C70D }}
          package: ./azure-arc-jumpstart-app/build/
